services:
  ledgercore-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5006:5005"
    expose:
      - "5005"
    environment:
      # API URLs - Use absolute URLs to directly connect to the backend
      # These can be overridden with environment variables
      - GRAPHQL_API_URL=${GRAPHQL_API_URL:-http://host.docker.internal:4000/graphql}
      - API_URL=${API_URL:-http://host.docker.internal:4000/api}
      
      # Neo4j Connection Defaults - These are handled by the backend
      - DEFAULT_NEO4J_DATABASE=${NEO4J_DATABASE:-bitcoin}
      - ALLOW_QUERIES_WITHOUT_LOGIN=true
      
      # Application Settings
      - DEFAULT_DASHBOARD_TITLE=LedgerCore Dashboard
      - DASHBOARD_HEADER_TITLE=LedgerCore Dashboard
      - DASHBOARD_HEADER_SUBTITLE=Blockchain Analytics
      - DASHBOARD_HEADER_COLOR=#0B297D
      - DASHBOARD_HEADER_TITLE_COLOR=#FFFFFF
    restart: unless-stopped
    networks:
      - ledgercore-network

  # NGINX service for routing
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - ledgercore-network

networks:
  ledgercore-network:
    name: bitcoin-to-neo4jdash_ledgercore-network
    external: true
