version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: ledgercore-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      # Neo4j connection settings
      - NEO4J_URI=${NEO4J_URI:-bolt://host.docker.internal:7687}
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-Neo4jPassword123!}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_here}
      # Explicitly disable mock driver
      - USE_MOCK_DRIVER=false
    networks:
      - ledgercore-network
    volumes:
      - backend-data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Frontend service (LedgerCore Dashboard)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ledgercore-frontend
    restart: unless-stopped
    ports:
      - "5005:5005"
    environment:
      # API URLs - Point to the backend service
      - API_URL=http://backend:4000/api
      - GRAPHQL_API_URL=http://backend:4000/graphql
      
      # Neo4j Connection Defaults - Use host.docker.internal to access Neo4j on the host
      - DEFAULT_NEO4J_URL=host.docker.internal
      - DEFAULT_NEO4J_PORT=7687
      - DEFAULT_NEO4J_DATABASE=neo4j
      
      # Application Settings
      - DEFAULT_DASHBOARD_TITLE=LedgerCore Dashboard
      - ALLOW_QUERIES_WITHOUT_LOGIN=true
      
      # Branding
      - DASHBOARD_HEADER_COLOR=#0B297D
      - DASHBOARD_HEADER_BUTTON_COLOR=#FFFFFF22
      - DASHBOARD_HEADER_TITLE_COLOR=#FFFFFF
    depends_on:
      - backend
    networks:
      - ledgercore-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  ledgercore-network:
    driver: bridge

volumes:
  backend-data:
