services:
  # Frontend service
  ledgercore-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5005"
    environment:
      # API URLs - Point to the backend GraphQL service
      # These can be overridden with environment variables
      - GRAPHQL_API_URL=${GRAPHQL_API_URL:-http://ledgercore-backend:4000/graphql}
      - API_URL=${API_URL:-http://ledgercore-backend:4000/api}
      
      # Neo4j Connection Defaults - These are handled by the backend
      - DEFAULT_NEO4J_DATABASE=${NEO4J_DATABASE:-bitcoin}
      
      # Application Settings
      - DEFAULT_DASHBOARD_TITLE=LedgerCore Dashboard
      - ALLOW_QUERIES_WITHOUT_LOGIN=true
      
      # Branding
      - DASHBOARD_HEADER_COLOR=#0B297D
      - DASHBOARD_HEADER_BUTTON_COLOR=#FFFFFF22
      - DASHBOARD_HEADER_TITLE_COLOR=#FFFFFF
    restart: unless-stopped
    networks:
      - ledgercore-network
    # This allows the container to find services on the host machine if needed
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:1.25-alpine
    container_name: ledgercore-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ledgercore-dashboard
    networks:
      - ledgercore-network

networks:
  ledgercore-network:
    driver: bridge
    # Use external network if your backend is in a separate docker-compose file
    external: true
    name: ${NETWORK_NAME:-ledgercore-network}
